import { CandidateProfile, JobRole, Question, VoiceAssessmentData, PracticalAssessmentData, EvidenceDocument, SkillGapItem, AuditLogItem } from '../types';

export const INITIAL_CANDIDATE: CandidateProfile = {
  id: 'cand-arun-01',
  userId: 'user-arun-01',
  name: 'Arun Kumar',
  age: 32,
  phone: '+91 98401 23456',
  location: 'Chennai, Tamil Nadu',
  avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  yearsOfExperience: 7,
  primaryTrade: 'Electrician',
  profileCompletion: 85,
  nsqfTargetLevel: 4,
  selectedJobRole: 'role-electrician-l4',
  experienceDescription: 'I have been working as an electrician for 7 years in domestic and commercial premises. I do conduit pipe laying, 3-phase wiring, distribution board assembly, MCB sizing, fan/light fittings, earthing resistance testing, and troubleshooting short circuits and fault isolation.',
  experienceConfidence: 92,
  assessmentStatus: 'under_assessor_review',
  extractedSkills: [
    { name: 'Electrical Wiring & Conduit Laying', category: 'core', confidence: 95, level: 'Advanced', verifiedByAssessor: true },
    { name: 'Distribution Board & MCB Installation', category: 'core', confidence: 91, level: 'Advanced', verifiedByAssessor: true },
    { name: 'Electrical Safety & PPE Compliance', category: 'safety', confidence: 96, level: 'Expert', verifiedByAssessor: true },
    { name: 'Circuit Testing & Multimeter Operation', category: 'diagnostic', confidence: 89, level: 'Intermediate', verifiedByAssessor: true },
    { name: 'Earth Resistance & Grounding', category: 'core', confidence: 88, level: 'Intermediate', verifiedByAssessor: true },
    { name: '3-Phase Motor Starter Fault Diagnosis', category: 'diagnostic', confidence: 72, level: 'Basic', verifiedByAssessor: false },
    { name: 'Customer Communication & Work Estimates', category: 'soft', confidence: 84, level: 'Intermediate', verifiedByAssessor: true },
  ],
  scores: {
    knowledge: 89,
    practical: 85,
    safety: 94,
    evidence: 88,
    communication: 81,
    overall: 87,
  },
  assessorRemarks: 'Candidate exhibits robust practical competency in domestic installations and exemplary safety protocol execution. Recommended for NSQF Level 4 RPL Certification with a minor bridge advisory in 3-phase industrial fault isolation.',
  assessorDecision: 'approved',
  certificateId: 'RPL-IND-2026-EL4-9842',
  certifiedDate: '06-Oct-2026',
};

export const JOB_ROLES: JobRole[] = [
  {
    id: 'role-electrician-l4',
    title: 'Electrician (Domestic & Commercial)',
    sector: 'Electrical & Electronics Sector Skill Council (ESSCI)',
    nsqfLevel: 4,
    matchScore: 92,
    description: 'Performs installation, testing, and maintenance of domestic and commercial electrical wiring, distribution boards, safety switches, and lighting systems as per Indian Standard (IS 732).',
    requiredSkills: ['Conduit Wiring', 'Earthing & Bonding', 'Safety Regulations', 'Testing Instruments', 'Fault Finding'],
    certifiedCandidatesCount: 14200,
    demandLevel: 'Very High',
    avgSalaryGrowth: '+38% post-certification',
  },
  {
    id: 'role-elec-maint-l4',
    title: 'Electrical Maintenance Technician',
    sector: 'Capital Goods Skill Council',
    nsqfLevel: 4,
    matchScore: 81,
    description: 'Conducts preventive, breakdown, and periodic electrical maintenance of motors, transformers, switchgear, and control panels in light manufacturing facilities.',
    requiredSkills: ['Preventive Maintenance', 'Control Panels', 'Motor Testing', 'Lock-Out Tag-Out (LOTO)'],
    certifiedCandidatesCount: 9850,
    demandLevel: 'High',
    avgSalaryGrowth: '+32% post-certification',
  },
  {
    id: 'role-solar-pv-l4',
    title: 'Solar PV System Installation Specialist',
    sector: 'Skill Council for Green Jobs (SCGJ)',
    nsqfLevel: 4,
    matchScore: 74,
    description: 'Mounts solar photovoltaic panels, connects solar inverters, runs DC/AC cabling, and installs net-metering systems under Pradhan Mantri Surya Ghar scheme.',
    requiredSkills: ['Solar Inverter Setup', 'DC Cabling', 'Roof Mounting', 'Grid Synchronization'],
    certifiedCandidatesCount: 6400,
    demandLevel: 'Very High',
    avgSalaryGrowth: '+45% post-certification',
  },
];

export const ASSESSMENT_QUESTIONS: Question[] = [
  {
    id: 'q1-safety-l1',
    roleId: 'role-electrician-l4',
    competency: 'Electrical Safety & PPE (Level 1)',
    difficultyLevel: 1,
    questionText: 'You are preparing to install a new 16A power socket in an existing residential building. What is the MANDATORY first step before touching any conductor?',
    questionTextTa: 'ஒரு குடியிருப்பில் புதிய 16A சாக்கெட் பொருத்துவதற்கு முன், வயரைத் தொடுவதற்கு முன்பு செய்ய வேண்டிய கட்டாய முதல் படி என்ன?',
    questionTextHi: 'एक आवासीय भवन में नया 16A सॉकेट लगाने से पहले, तारों को छूने से पूर्व पहला अनिवार्य कदम क्या होना चाहिए?',
    options: [
      { id: 'opt-a', text: 'Select matching switch plate color', textTa: 'பொருத்தமான சுவிட்ச் தகடு நிறத்தைத் தேர்ந்தெடுக்கவும்', textHi: 'स्विच प्लेट का रंग चुनना' },
      { id: 'opt-b', text: 'Isolate main supply breaker (MCB) and verify zero voltage with tester', textTa: 'முக்கிய மின் இணைப்பை (MCB) அணைத்து, டெஸ்டர் மூலம் மின்சாரம் இல்லை என்பதை உறுதி செய்யவும்', textHi: 'मुख्य एमसीबी बंद करें और टेस्टर से शून्य वोल्टेज जांचें' },
      { id: 'opt-c', text: 'Measure room ambient temperature', textTa: 'அறையின் வெப்பநிலையை அளவிடவும்', textHi: 'कमरे का तापमान मापना' },
      { id: 'opt-d', text: 'Directly strip the live cable using bare pliers', textTa: 'இன்சுலேஷன் இல்லாத பிளையர் கொண்டு வயரை உரிக்கவும்', textHi: 'खुले प्लायर्स से सीधे तार छीलना' },
    ],
    correctOptionId: 'opt-b',
    explanation: 'Lockout/Tagout and isolating the incoming main supply followed by testing for zero potential is mandatory under Indian Electricity Rules 1956 to prevent electrocution.',
    simpleExplanation: 'Always turn off the main switch and check with a tester so no electric shock can happen.',
    simpleExplanationTa: 'மின் அதிர்ச்சி ஏற்படாமல் இருக்க எப்போதும் மெயின் சுவிட்சை ஆஃப் செய்து டெஸ்டர் மூலம் சரிபார்க்கவும்.',
    simpleExplanationHi: 'करंट से बचने के लिए हमेशा मेन स्विच बंद करें और टेस्टर से जांचें।',
  },
  {
    id: 'q2-wiring-l2',
    roleId: 'role-electrician-l4',
    competency: 'Wiring Practices & Color Codes (Level 2)',
    difficultyLevel: 2,
    questionText: 'As per standard Indian Single-Phase AC wiring conventions (IS 732), what are the designated insulation colors for Phase (Line), Neutral, and Earth conductors?',
    questionTextTa: 'இந்திய நிலையான ஒற்றை-கட்ட (Single Phase) மின் வயரிங் விதிகளின்படி, Phase (Line), Neutral மற்றும் Earth கம்பிகளுக்கான வண்ணங்கள் எவை?',
    questionTextHi: 'भारतीय मानक सिंगल-फेज एसी वायरिंग नियमों (IS 732) के अनुसार फेज, न्यूट्रल और अर्थ तारों के निर्धारित रंग क्या हैं?',
    options: [
      { id: 'opt-a', text: 'Phase: Red/Brown | Neutral: Black/Blue | Earth: Green/Green-Yellow', textTa: 'பேஸ்: சிகப்பு/பிரவுன் | நியூட்ரல்: கருப்பு/நீலம் | எர்த்: பச்சை/மஞ்சள்-பச்சை', textHi: 'फेज: लाल/भूरा | न्यूट्रल: काला/नीला | अर्थ: हरा/पीला-हरा' },
      { id: 'opt-b', text: 'Phase: Green | Neutral: Red | Earth: Black', textTa: 'பேஸ்: பச்சை | நியூட்ரல்: சிகப்பு | எர்த்: கருப்பு', textHi: 'फेज: हरा | न्यूट्रल: लाल | अर्थ: काला' },
      { id: 'opt-c', text: 'Phase: Yellow | Neutral: White | Earth: Red', textTa: 'பேஸ்: மஞ்சள் | நியூட்ரல்: வெள்ளை | எர்த்: சிகப்பு', textHi: 'फेज: पीला | न्यूट्रल: सफेद | अर्थ: लाल' },
      { id: 'opt-d', text: 'Any color can be used interchangeably', textTa: 'எந்த நிறத்தையும் எப்படி வேண்டுமானாலும் பயன்படுத்தலாம்', textHi: 'किसी भी रंग का उपयोग किया जा सकता है' },
    ],
    correctOptionId: 'opt-a',
    explanation: 'In India, Phase is Red/Brown, Neutral is Black or Royal Blue, and Protective Earth is mandatory Green with Yellow stripes.',
    simpleExplanation: 'Red/Brown carries current (Phase), Black/Blue returns current (Neutral), and Green protects against leakage (Earth).',
    simpleExplanationTa: 'சிகப்பு - மின்சாரம் வரும் கம்பி, கருப்பு - திரும்பும் கம்பி, பச்சை - பூமி பாதுகாப்பு கம்பி.',
    simpleExplanationHi: 'लाल फेज (करंट), काला न्यूट्रल और हरा अर्थिंग सुरक्षा तार होता है।',
  },
  {
    id: 'q3-fault-l3',
    roleId: 'role-electrician-l4',
    competency: 'Fault Diagnosis & Earth Leakage (Level 3)',
    difficultyLevel: 3,
    questionText: 'An RCCB (Residual Current Circuit Breaker) in a house trips continuously as soon as an electric water heater is switched on. What is the most probable root cause?',
    questionTextTa: 'ஒரு வீட்டில் வாட்டர் ஹீட்டர் ஆன் செய்தவுடன் RCCB உடனே ட்ரிப் (Trip) ஆகிறது. இதற்கு மிகவும் சாத்தியமான காரணம் என்ன?',
    questionTextHi: 'गीजर ऑन करते ही घर का आरसीसीबी (RCCB) बार-बार ट्रिप हो जाता है। इसका सबसे संभावित कारण क्या है?',
    options: [
      { id: 'opt-a', text: 'The heater heating element has insulation breakdown leaking current to ground/water', textTa: 'ஹீட்டரின் ஹீட்டிங் எலிமெண்ட்டில் இன்சுலேஷன் பழுதாகி பாடி அல்லது தண்ணீருக்கு மின் கசிவு ஏற்படுகிறது', textHi: 'हीटर के एलिमेंट में इंसुलेशन खराबी के कारण अर्थ/पानी में करंट लीकेज हो रहा है' },
      { id: 'opt-b', text: 'The room ceiling fan is running at high speed', textTa: 'அறையின் மின்விசிறி வேகமாக சுழல்கிறது', textHi: 'कमरे का पंखा तेज चल रहा है' },
      { id: 'opt-c', text: 'The utility meter is recording unit usage', textTa: 'மின்சார மீட்டர் இயங்குகிறது', textHi: 'बिजली मीटर चालू है' },
      { id: 'opt-d', text: 'The water temperature is set too cold', textTa: 'தண்ணீர் வெப்பநிலை குறைவாக உள்ளது', textHi: 'पानी बहुत ठंडा है' },
    ],
    correctOptionId: 'opt-a',
    explanation: 'RCCBs detect differential currents between Phase and Neutral (typically 30mA threshold). When a faulty heating element leaks current to the earthed body/water tank, the RCCB trips instantly to save life.',
    simpleExplanation: 'Current is leaking from the heater rod to earth/water. The RCCB senses this leakage and cuts power to protect human life.',
    simpleExplanationTa: 'ஹீட்டர் கம்பியிலிருந்து தண்ணீருக்கு மின்சாரம் கசிகிறது. ஆபத்தைத் தடுக்க RCCB மின் இணைப்பைத் துண்டிக்கிறது.',
    simpleExplanationHi: 'गीजर के रॉड से पानी या बॉडी में करंट लीक हो रहा है, जिसे पकड़कर आरसीसीबी सुरक्षा के लिए बंद हो जाता है।',
  },
  {
    id: 'q4-troubleshoot-l4',
    roleId: 'role-electrician-l4',
    competency: 'Advanced Industrial Troubleshooting (Level 4)',
    difficultyLevel: 4,
    questionText: 'When troubleshooting a 3-phase induction motor that hums loudly but fails to rotate on pressing the DOL starter, what should you verify with a clamp meter and multimeter?',
    questionTextTa: '3-பேஸ் மோட்டார் ஸ்டார்ட்டர் அழுத்தியதும் சத்தம் மட்டும் போட்டு சுழலவில்லை என்றால், மல்டிமீட்டர் மூலம் முதலில் எதைச் சரிபார்க்க வேண்டும்?',
    questionTextHi: '3-फेज मोटर चालू करने पर केवल हमिंग की आवाज आती है लेकिन घूमती नहीं है। मल्टीमीटर से सबसे पहले क्या जांचेंगे?',
    options: [
      { id: 'opt-a', text: 'Single-phasing condition (absence of one phase voltage/blown backup fuse)', textTa: 'சிங்கிள்-பேசிங் நிலை (ஒரு பேஸ் வோல்டேஜ் இல்லாமை அல்லது ஃபியூஸ் போயிருத்தல்)', textHi: 'सिंगल-फेजिंग स्थिति (एक फेज का गायब होना या फ्यूज उड़ना)' },
      { id: 'opt-b', text: 'Check motor paint surface finish', textTa: 'மோட்டாரின் பெயிண்ட் நிலையைச் சரிபார்த்தல்', textHi: 'मोटर का बाहरी रंग देखना' },
      { id: 'opt-c', text: 'Increase supply frequency artificially', textTa: 'மின் அதிர்வெண்ணை அதிகரிப்பது', textHi: 'सप्लाई फ्रीक्वेंसी बढ़ाना' },
      { id: 'opt-d', text: 'Swap live phase and earth wires', textTa: 'பேஸ் மற்றும் எர்த் கம்பிகளை மாற்றி இணைப்பது', textHi: 'फेज और अर्थ तार आपस में बदलना' },
    ],
    correctOptionId: 'opt-a',
    explanation: 'Single phasing occurs when one line conductor is open. The motor experiences an unbalanced alternating field, draws heavy locked-rotor current, hums, and cannot generate starting torque.',
    simpleExplanation: 'Check if one of the three phases is missing due to a blown fuse or loose contact in the starter.',
    simpleExplanationTa: 'மூன்று பேஸ்களில் ஒரு பேஸ் வோல்டேஜ் விடுபட்டுள்ளதா என்பதைச் சரிபார்க்கவும்.',
    simpleExplanationHi: 'जांचें कि तीन में से कोई एक फेज कट तो नहीं गया है (फ्यूज या कॉन्टैक्टर से)।',
  },
];

export const VOICE_DEMO_DATA: VoiceAssessmentData = {
  promptQuestion: "How would you identify and isolate a faulty electrical circuit causing frequent tripping in a domestic distribution board?",
  promptQuestionTa: "ஒரு வீட்டில் அடிக்கடி MCB ட்ரிப் ஆகும் பழுதுபட்ட மின் சுற்றை எவ்வாறு கண்டறிந்து தனிமைப்படுத்துவீர்கள்?",
  promptQuestionHi: "घर के डिस्ट्रीब्यूशन बोर्ड में बार-बार ट्रिप होने वाले खराब सर्किट को आप कैसे पहचानेंगे और अलग करेंगे?",
  transcript: "First, I will wear rubber insulated safety footwear and gloves. I turn off all sub-circuit MCBs on the DB. Next, I reset the main ELCB/RCCB and main isolator. Then, I switch ON each individual circuit breaker one by one. The specific circuit that instantly trips the breaker is identified as the fault branch. I keep that faulty MCB OFF, isolate its neutral, and check for short-circuit between Phase-Neutral or Phase-Earth using a digital multimeter on continuity mode. I then inspect all appliances and junction boxes on that line.",
  durationSeconds: 38,
  scores: {
    technicalKnowledge: 89,
    procedureUnderstanding: 84,
    safetyAwareness: 94,
    communication: 81,
  },
  keyConceptsIdentified: [
    'Sub-circuit sequential isolation',
    'RCCB/ELCB trip correlation',
    'Multimeter continuity testing',
    'Phase-Neutral / Phase-Earth short detection',
    'Junction box inspection',
  ],
  safetyMentions: [
    'Insulated gloves & footwear',
    'Main supply isolation before opening panel',
    'Zero-energy state verification',
  ],
};

export const PRACTICAL_DEMO_DATA: PracticalAssessmentData = {
  taskTitle: 'Safe Installation of 1-Way Switch with 16A Solderless Socket & Continuity Check',
  taskInstructions: 'Wear recommended PPE (gloves/glasses), isolate test rig power, strip 1.5 sq mm copper wire to 10mm without copper strand nicking, fasten securely into terminal lugs, and verify insulation integrity.',
  duration: '00:48',
  videoThumbnail: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&auto=format&fit=crop&q=80',
  scores: {
    taskCompletion: 78,
    safetyCompliance: 91,
    toolHandling: 88,
    procedureAccuracy: 84,
    overallPractical: 85,
  },
  observations: [
    {
      timestamp: '00:04',
      label: 'PPE Compliance: 1000V Insulated Gloves',
      status: 'passed',
      box: { x: 18, y: 35, width: 26, height: 38 },
      description: 'Candidate verified wearing Class 0 certified electrical hand gloves.',
    },
    {
      timestamp: '00:09',
      label: 'Tool Selection: VDE Insulated Terminal Screwdriver',
      status: 'passed',
      box: { x: 55, y: 40, width: 22, height: 30 },
      description: 'Correct insulated screwdriver selected matching terminal slot width.',
    },
    {
      timestamp: '00:18',
      label: 'Wire Stripping: Zero Strand Nicking',
      status: 'passed',
      box: { x: 38, y: 48, width: 28, height: 32 },
      description: 'Stripper gauge calibrated accurately; no copper conductor deformation detected.',
    },
    {
      timestamp: '00:32',
      label: 'Notice: Pre-testing Neutral Isolation Step',
      status: 'warning',
      box: { x: 30, y: 22, width: 35, height: 45 },
      description: 'Candidate connected phase first before tightening neutral retention clamp.',
    },
  ],
  timelineEvents: [
    { time: '00:04', title: 'Safety Gear & Workplace Setup', status: 'success', detail: 'Insulated mat, safety glasses, and 1000V gloves verified by CV detector.' },
    { time: '00:09', title: 'Tool Calibration & Inspection', status: 'success', detail: 'Tester, insulation stripper, and torque screwdriver verified.' },
    { time: '00:18', title: 'Conductor Preparation & Stripping', status: 'success', detail: 'Clean 10mm strip without damaging core copper strands.' },
    { time: '00:32', title: 'Switch Terminal Fastening', status: 'warning', detail: 'Slight looseness noted on terminal 2 before final torque verification.' },
    { time: '00:44', title: 'Post-Install Continuity Verification', status: 'success', detail: 'Zero ohm resistance on closed circuit; infinite resistance on open.' },
  ],
};

export const EVIDENCE_DOCUMENTS: EvidenceDocument[] = [
  {
    id: 'doc-01',
    fileName: 'ABC_Electrical_Contractors_Experience_Letter.pdf',
    fileType: 'experience_letter',
    fileSize: '1.4 MB',
    uploadDate: '02-Oct-2026',
    aiVerificationStatus: 'verified',
    aiRelevanceScore: 94,
    extractedData: {
      employerOrContractor: 'ABC Electrical Works & Infrastructure Pvt Ltd, Chennai',
      statedRole: 'Senior Domestic & Commercial Electrician',
      duration: 'May 2019 – Present (7 Years)',
      detectedSkills: ['Conduit Wiring', 'DB Dressing', 'Earth Testing', 'LT Switchgear Setup'],
      tamperingRisk: 'Low',
    },
  },
  {
    id: 'doc-02',
    fileName: 'Residential_Project_Site_Photos.jpg',
    fileType: 'site_photo',
    fileSize: '3.8 MB',
    uploadDate: '03-Oct-2026',
    aiVerificationStatus: 'verified',
    aiRelevanceScore: 89,
    extractedData: {
      employerOrContractor: 'Direct Client Work: 12-Unit Apartment Complex',
      statedRole: 'Lead Wiring Craftsman',
      duration: 'Completed Nov 2025',
      detectedSkills: ['Main Distribution Panel Wiring', 'Cable Tray Route Installation'],
      tamperingRisk: 'Low',
    },
  },
  {
    id: 'doc-03',
    fileName: 'Contractor_Affidavit_Declaration.pdf',
    fileType: 'contractor_affidavit',
    fileSize: '820 KB',
    uploadDate: '04-Oct-2026',
    aiVerificationStatus: 'needs_review',
    aiRelevanceScore: 82,
    extractedData: {
      employerOrContractor: 'Licensed Contractor (Lic No. TN/EB/44910)',
      statedRole: 'Apprentice to Senior Wireman',
      duration: '2017 – 2019',
      detectedSkills: ['Basic Wiring', 'Appliance Repair'],
      tamperingRisk: 'Low',
    },
  },
];

export const SKILL_GAPS: SkillGapItem[] = [
  {
    skillName: 'Electrical Safety & PPE Regulations',
    currentLevelScore: 94,
    requiredLevelScore: 80,
    status: 'PASS',
    recommendedBridgeModule: {
      title: 'Advanced High-Voltage Safety Standards (Refresher)',
      duration: '20 Mins',
      partner: 'Skill India Digital Hub',
      linkUrl: '#',
    },
  },
  {
    skillName: 'Domestic & Commercial Conduit Wiring',
    currentLevelScore: 92,
    requiredLevelScore: 75,
    status: 'PASS',
    recommendedBridgeModule: {
      title: 'IS 732 Wiring Standards & Smart Home Conduit Systems',
      duration: '35 Mins',
      partner: 'ESSCI Sector Council',
      linkUrl: '#',
    },
  },
  {
    skillName: 'Distribution Board & RCCB Installation',
    currentLevelScore: 89,
    requiredLevelScore: 80,
    status: 'PASS',
    recommendedBridgeModule: {
      title: 'Surge Protection Devices (SPD) Sizing and Wiring',
      duration: '25 Mins',
      partner: 'National Skill Development Corporation',
      linkUrl: '#',
    },
  },
  {
    skillName: '3-Phase Motor Starters & Industrial Fault Diagnosis',
    currentLevelScore: 72,
    requiredLevelScore: 80,
    status: 'GAP',
    recommendedBridgeModule: {
      title: 'Star-Delta Starter Wiring & Overload Relay Troubleshooting',
      duration: '45 Mins Modular Video',
      partner: 'Skill India / NCVET FastTrack',
      linkUrl: '#',
    },
  },
  {
    skillName: 'Customer Communication & Cost Estimation',
    currentLevelScore: 81,
    requiredLevelScore: 70,
    status: 'PASS',
    recommendedBridgeModule: {
      title: 'Digital Invoicing & Bill of Quantities (BOQ) Basics',
      duration: '15 Mins',
      partner: 'MSDE Entrepreneurship Cell',
      linkUrl: '#',
    },
  },
];

export const ASSESSOR_CANDIDATE_QUEUE: CandidateProfile[] = [
  INITIAL_CANDIDATE,
  {
    id: 'cand-meera-02',
    userId: 'user-meera-02',
    name: 'Meera Devi',
    age: 29,
    phone: '+91 94432 87654',
    location: 'Coimbatore, Tamil Nadu',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    yearsOfExperience: 5,
    primaryTrade: 'Apparel & Tailoring',
    profileCompletion: 90,
    nsqfTargetLevel: 3,
    selectedJobRole: 'Self-Employed Tailor (NSQF Level 3)',
    experienceDescription: '5 years stitching blouses, salwar suits, industrial uniforms, pattern drafting, and operating motorized sewing machines.',
    experienceConfidence: 94,
    assessmentStatus: 'under_assessor_review',
    extractedSkills: [
      { name: 'Pattern Drafting & Cutting', category: 'core', confidence: 92, level: 'Advanced' },
      { name: 'Sewing Machine Maintenance', category: 'tool', confidence: 88, level: 'Intermediate' },
      { name: 'Quality Inspection & Finishing', category: 'safety', confidence: 90, level: 'Advanced' },
    ],
    scores: {
      knowledge: 86,
      practical: 91,
      safety: 90,
      evidence: 84,
      communication: 85,
      overall: 87,
    },
    assessorDecision: 'pending',
  },
  {
    id: 'cand-rajesh-03',
    userId: 'user-rajesh-03',
    name: 'Rajesh Patel',
    age: 38,
    phone: '+91 98250 11223',
    location: 'Surat, Gujarat',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    yearsOfExperience: 9,
    primaryTrade: 'Shielded Metal Arc Welder (SMAW)',
    profileCompletion: 80,
    nsqfTargetLevel: 4,
    selectedJobRole: 'SMAW Welder (NSQF Level 4)',
    experienceDescription: '9 years welding MS structural pipes, pressure vessel flanges, flux core welding, gas cutting.',
    experienceConfidence: 89,
    assessmentStatus: 'under_assessor_review',
    extractedSkills: [
      { name: 'SMAW 3G/4G Position Welding', category: 'core', confidence: 96, level: 'Expert' },
      { name: 'Welding Safety & Gas Handling', category: 'safety', confidence: 94, level: 'Expert' },
      { name: 'Non-Destructive Dye Penetrant Testing', category: 'diagnostic', confidence: 76, level: 'Intermediate' },
    ],
    scores: {
      knowledge: 82,
      practical: 93,
      safety: 92,
      evidence: 80,
      communication: 76,
      overall: 85,
    },
    assessorDecision: 'pending',
  },
  {
    id: 'cand-suresh-04',
    userId: 'user-suresh-04',
    name: 'Suresh Nair',
    age: 35,
    phone: '+91 97455 33445',
    location: 'Kochi, Kerala',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    yearsOfExperience: 6,
    primaryTrade: 'Automotive Mechanic (2-Wheeler / 4-Wheeler)',
    profileCompletion: 88,
    nsqfTargetLevel: 4,
    selectedJobRole: 'Auto Service Technician (Level 4)',
    experienceDescription: '6 years vehicle servicing, brake overhaul, engine compression checking, EFI diagnostics and sensor replacement.',
    experienceConfidence: 91,
    assessmentStatus: 'reassessment_needed',
    extractedSkills: [
      { name: 'Engine Tuning & Compression Check', category: 'core', confidence: 88, level: 'Advanced' },
      { name: 'Hydraulic Brake Bleeding', category: 'core', confidence: 86, level: 'Intermediate' },
      { name: 'OBD-II Diagnostic Scanning', category: 'diagnostic', confidence: 68, level: 'Basic' },
    ],
    scores: {
      knowledge: 74,
      practical: 80,
      safety: 85,
      evidence: 78,
      communication: 72,
      overall: 78,
    },
    assessorDecision: 'reassessment',
    assessorRemarks: 'Strong mechanical skills demonstrated; reassessment advised specifically on electronic OBD-II scanner diagnostics.',
  },
];

export const AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'log-01',
    timestamp: '06-Oct-2026 10:14 AM',
    actor: 'Priya Sharma (Assessor ID: ASS-TN-094)',
    role: 'Assessor',
    action: 'Certification Approval Signed',
    details: 'Approved candidate Arun Kumar (cand-arun-01) for NSQF Level 4 RPL Electrician Certification.',
  },
  {
    id: 'log-02',
    timestamp: '06-Oct-2026 09:48 AM',
    actor: 'AI Skill Engine v3.4',
    role: 'System',
    action: 'Computer Vision Analysis Generated',
    details: 'Processed practical demonstration video for cand-arun-01. Score: 85% with 4 key safety/tool milestones verified.',
  },
  {
    id: 'log-03',
    timestamp: '06-Oct-2026 09:30 AM',
    actor: 'AI Voice Engine (Whisper-Gov MultiLang)',
    role: 'System',
    action: 'Voice Response Transcribed & Evaluated',
    details: 'Transcribed audio for cand-arun-01 in Tamil/English mix. Technical Knowledge Score: 89%.',
  },
  {
    id: 'log-04',
    timestamp: '06-Oct-2026 09:12 AM',
    actor: 'Arun Kumar',
    role: 'Candidate',
    action: 'Evidence Documents Submitted',
    details: 'Uploaded experience letter (ABC Electrical) and site installation photos.',
  },
];
